### ISSUE TITLE
What means "folder called CDM with your CDM inside"?

### ISSUE THREAD

**Issue by slrslr** [DevLARLEY/MultiMPDTool#4]
Hello,

I am trying to download a video from viki.com, i can find a .mpd url in a web browser dev. console (F12 key), Console tab.
And that seems to be what this Multi MPDTool accepts.

But in this tool installation manual (README.md), I do not understand this part:
Create a folder called CDM with your CDM inside

I am unsure what is my CDM and how to obtain it? Are there please anywhere exact steps for a layman on Linux Debian?

What I have found so far is that it means "Content Decryption Module" and that https://cdrm-project.com can be used as a replacement. Yet it is not helpful in telling what i am filling wrong and which format is correct.

git clone https://github.com/DevLARLEY/MultiMPDTool.git && cd MultiMPDTool && pip3 install -r requirements.txt
$ python3 multimpdtool.py
```
Traceback (most recent call last):
  File "/dev/shm/MultiMPDTool/multimpdtool.py", line 45, in <module>
    ) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by DevLARLEY** [comment]
I don't want to provide support for this tool, it's terrible
