### ISSUE TITLE
About file rename

### ISSUE THREAD

**Issue by vendettazz** [DevLARLEY/MultiMPDTool#5]
Hello again,
I use multimpdtool software. it works very well, I wonder if there is a module that we can rename the downloaded mpd videos after making ‘mux’. can you help?

**Comment by DevLARLEY** [comment]
I could add that but this tool is outdated, so I don't want add any more features

**Comment by vendettazz** [comment]
I understand, can you write a module for rename if it won't take you too much effort? or can you offer an alternative?

**Comment by DevLARLEY** [comment]
What do you mean by 'module'?

**Comment by vendettazz** [comment]
I mean, can you modify it so I can rename it? If it won't keep you too busy.

**Comment by DevLARLEY** [comment]
So you want to enter a name of the output file while the program is running?

**Comment by vendettazz** [comment]
yes, in the last option I would like to write the name of the output file

**Comment by vendettazz** [comment]
I already enter all the options manually. I would like to manually enter and change the name of the output file. because I download 5-6 mpd files one after the other. after downloading, I compare them one by one from the source video and change their names. it would be very nice if there is a name adding part in it.

**Comment by DevLARLEY** [comment]
I've updated the script

**Comment by vendettazz** [comment]
thank you very much you are a legend
