### ISSUE TITLE
about udemy

### ISSUE THREAD

**Issue by vendettazz** [DevLARLEY/MultiMPDTool#6]
Hello again, I tried to use the MultiMPDTool programme for udemy but when I type mpd url it gives ppsh not found error. Can you try this tool for Udemy?

**Comment by DevLARLEY** [comment]
1. MultiMPDTool has terrible support for websites (I don't want people to use it)
2. Use WidevineFetch to get the keys
3. Use [https://github.com/Puyodead1/udemy-downloader](https://github.com/Puyodead1/udemy-downloader) to download the videos

**Comment by vendettazz** [comment]
thanks a lot
