### ISSUE TITLE
cant download mpd file

### ISSUE THREAD

**Issue by vendettazz** [DevLARLEY/MultiMPDTool#7]
i was able to download gnomon videos with your current version of gnomon without any problem but last night i got yt-dlp error. i updated yt-dlp version but i get the same error. can you help? yt-dlp version : yt_dlp-2024.10.1.232843
![Screenshot_1](https://github.com/user-attachments/assets/43dd376e-a5db-4e2a-853f-03fcbcf3abed)

**Comment by DevLARLEY** [comment]
That's a yt-dlp issue, report it on their github
